-- Run this in Supabase: SQL Editor → New query → paste → Run
-- Creates tables for Lifts and Mood so you and Jolene can track from the site.

-- 1. Lifts table (gym / muscle groups)
CREATE TABLE IF NOT EXISTS public.lifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_name TEXT NOT NULL,
  muscles TEXT NOT NULL,
  log_date DATE NOT NULL DEFAULT (CURRENT_DATE),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.lifts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon read lifts" ON public.lifts FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon insert lifts" ON public.lifts FOR INSERT TO anon WITH CHECK (true);

-- 2. Mood table (how you're feeling 1–10 + optional note)
CREATE TABLE IF NOT EXISTS public.mood (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_name TEXT NOT NULL,
  score INT NOT NULL CHECK (score >= 1 AND score <= 10),
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.mood ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon read mood" ON public.mood FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon insert mood" ON public.mood FOR INSERT TO anon WITH CHECK (true);

-- 3. Question of the day: one response per person per day (upsert by date + from_name)
CREATE TABLE IF NOT EXISTS public.qotd_responses (
  response_date DATE NOT NULL,
  from_name TEXT NOT NULL,
  response TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (response_date, from_name)
);

ALTER TABLE public.qotd_responses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon read qotd" ON public.qotd_responses FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon insert qotd" ON public.qotd_responses FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon update qotd" ON public.qotd_responses FOR UPDATE TO anon USING (true) WITH CHECK (true);
